PATCH     https://apiraje.herokuapp.com/api/v1/employee
Content-Type: application/json

{
"_id": "8a237499-0bb5-4344-b182-1c54b45df858",
"Fname": "Visganeshhal",
"Lname": "Ghadage",
"Depname": "OS",
"Salary": 7000000000
}